Slicing arrays means taking elements from one index to another
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step]. [0,default length, 1]

If we don't pass start its considered 0 by default

If we don't pass end its considered default length of array in that dimension

If we don't pass step its considered 1

Note: The result includes the start index, but excludes the end index.

In [2]:
! pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
#Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
#start = 1 ,element at index 1 = 2 
#end = 5 → stops before index 5 (so index 5 = element 6 is NOT included ).
print(arr[1:5])  

[2 3 4 5]


In [4]:
#Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [5]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0:4])

[1 2 3 4]


Negative Slicing

In [ ]:
#Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[-3:-1])                  #neg regx starts from -1

[5 6]


Slicing with Step


In [ ]:
#Return every other element from index 1 to index 5:
#Tala ko eg ma value start index 1= 2, end chai index 5= 6
#step =2 vaneko pick every 2nd element

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
# Return every other element from the entire array:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])        #start by default 0, end by default length of array ani step 2

[1 3 5 7]


Slicing 2-D Arrays

In [ ]:
#From the second element, slice elements from index 1 to index 4 (not included):
#vaneko 2nd row ko 7 to 10 but end not included

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])    

[7 8 9]


In [14]:
#From both elements, return index 2:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])  #0:2 → rows 0 and 1 (end exclusive, so rows 0 and 1 included) 
                      # 2 → column index 2 → 3rd column



[3 8]


In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])   #0:2 vaneko row ani 1:4 vaneko index



[[2 3 4]
 [7 8 9]]
