Copy- new array, changes gareko original ma kei effect hunna ani vice versa

View - view of an original array, view ma change gareko will effect original array and vice versa

In [ ]:
#Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42    #index 0 ma replace with 42 
            #The copy SHOULD NOT be affected by the changes made to the original array.
print(arr)   #display original
print(x)       #displays copy

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
                         #The view SHOULD be affected by the changes made to the original array.

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [4]:
#Make a view, change the view, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


Checking if array owns its data

copy- owns view - doesnot own

tesko lagi base attribute use garne that returns none if the array owns the data

otherwise, base attribute refers to the original data

In [ ]:
#Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)  #owns so none
print(y.base)  #doesnot own so original data display


None
[1 2 3 4 5]
