Creating Arrays

In [2]:
! pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))         #type() is a bulit in python function that tells us the type of object passed to it

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1,2,3,4,5))  #we can pass list,tuples or any array-like object into array()
print(arr)

[1 2 3 4 5]


Dimensions in Array

0-D Array or Scalars vaneko elements in array.
Each value in an array is a 0 D array

In [5]:
arr = np.array(43)
print(arr)

43


1D array has 0 d array as its elements and is called uni -dimensional as well

In [ ]:
arr = np.array([1,2,3,4,5]) #Create a 1-D array containing the values 1,2,3,4,5:
print(arr)

[1 2 3 4 5]


2D array has 1D elements and used to represent matrix or 2nd order tensors

Matrix operation ko lagi numpy.mat use huncha

[[ ]] - bracket used

In [7]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


3-D array is An array that has 2-D arrays (matrices) as its elements 

These are often used to represent a 3rd order tensor.
[[[ ]]] -brackets used

In [ ]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?
ndim attribute is used to return an integer jasle kati oota dimensions cha array ma vanncha

In [11]:
a = np.array(42)
b = np.array ([1,2,3,4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays

array ma jati oota pani dimensions huna sakcha.
ndim le chai kati oota cha vanera vancha
ndimn le chai hamlai define garna dencha

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr)
print('number of dimensions :', arr.ndim)

[[1 2 3 4]]
number of dimensions : 2
