Data Types in python

strings: represents text and quote marks bhitra lekhcha eg:"Hello"
integer: integer numbers eg:1,2,-3,-9
float: real numbers eg: 1.2, 3.3
boolean: True or false
complex : A number with a real part and an imaginary part, written as a + bj.
complex numbers eg:1.0+2.0j

Data Types in Numpy
NumPy has some extra data types, and refer to data types with one character :
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [15]:
import numpy as np

Checking the Data Type of an Array

dtype le kun data type of array vancha.
used as arr.dtype

In [16]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
#Get the data type of an array containing strings:
#< → little-endian (how bytes are stored in memory, usually you don’t worry about it)
#U → Unicode string
#5 → maximum number of characters each string can have
#So <U5 = Unicode string of max length 5.

arr = np.array(['hello','world'])
print(arr.dtype)    

SyntaxError: cannot assign to comparison (1998309807.py, line 6)

Creating Arrays With a Defined Data Type

array() function bhitra dtype use garera data type lekhna milcha j bhayeni

In [ ]:
#dtype='S' → tells NumPy to store all elements as bytes/strings, not numbers.

#So even though you wrote numbers [1, 2, 3, 4], they become byte-strings.
#|S1 → data type = string of length 1

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#Create an array with data type 4 bytes integer:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


What if a Value Can Not Be Converted?

ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [ ]:
arr = np.array(['a', '2', '3'], dtype='i')
#A non integer string like 'a' can not be converted to integer (will raise an error):


ValueError: invalid literal for int() with base 10: 'a'

Converting Data Type on Existing Arrays

astype()- changes the data type of an existing array by making a copy of that array

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
#Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.2,1.3,1.4])
eg = arr.astype('i')
print(eg)
print(eg.dtype)

[1 1 1]
int32


In [20]:
#Change data type from float to integer by using int as parameter value:
arr = np.array([1.2,1.3,1.4])
eg = arr.astype('int')
print(eg)
print(eg.dtype)


[1 1 1]
int64


astype(bool) converts each element to a boolean:

0 → False

any non-zero number → True (negative or positive doesn’t matter)

In [ ]:
#From int to boolean

arr = np.array([1,2,3])
                     
eg=arr.astype('bool')
print(eg)
print(eg.dtype)

[ True  True  True]
bool


In [22]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]
